version: '3.8'

services:
  # ADK-enabled Backend Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"  # FastAPI Backend
      - "8000:8000"  # ADK API Server
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - FIRESTORE_EMULATOR_HOST=firestore:8080
      - ADK_BASE_URL=http://localhost:8000
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - firestore
    networks:
      - chatbot-network

  # Streamlit Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - chatbot-network

  # Firestore Emulator (for development)
  firestore:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:latest
    ports:
      - "8080:8080"
      - "4000:4000"
    command: >
      sh -c "gcloud emulators firestore start 
             --host-port=0.0.0.0:8080 
             --rules-file=/dev/null"
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge

volumes:
  uploads:
